class Country {
  final String name;
  final String flag;
  final String dialCode;
  final String isoCode;
  final int maxLength;

  const Country({
    required this.name,
    required this.flag,
    required this.dialCode,
    required this.isoCode,
    this.maxLength = 15,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Country && isoCode == other.isoCode;

  @override
  int get hashCode => isoCode.hashCode;
}

class CountryData {
  static const List<Country> countries = [
    Country(name: 'Afghanistan', flag: '🇦🇫', dialCode: '+93', isoCode: 'AF'),
    Country(name: 'Albania', flag: '🇦🇱', dialCode: '+355', isoCode: 'AL'),
    Country(name: 'Algeria', flag: '🇩🇿', dialCode: '+213', isoCode: 'DZ'),
    Country(name: 'Andorra', flag: '🇦🇩', dialCode: '+376', isoCode: 'AD'),
    Country(name: 'Angola', flag: '🇦🇴', dialCode: '+244', isoCode: 'AO'),
    Country(name: 'Argentina', flag: '🇦🇷', dialCode: '+54', isoCode: 'AR'),
    Country(name: 'Armenia', flag: '🇦🇲', dialCode: '+374', isoCode: 'AM'),
    Country(name: 'Australia', flag: '🇦🇺', dialCode: '+61', isoCode: 'AU'),
    Country(name: 'Austria', flag: '🇦🇹', dialCode: '+43', isoCode: 'AT'),
    Country(name: 'Azerbaijan', flag: '🇦🇿', dialCode: '+994', isoCode: 'AZ'),
    Country(name: 'Bahamas', flag: '🇧🇸', dialCode: '+1242', isoCode: 'BS'),
    Country(name: 'Bahrain', flag: '🇧🇭', dialCode: '+973', isoCode: 'BH'),
    Country(name: 'Bangladesh', flag: '🇧🇩', dialCode: '+880', isoCode: 'BD'),
    Country(name: 'Barbados', flag: '🇧🇧', dialCode: '+1246', isoCode: 'BB'),
    Country(name: 'Belarus', flag: '🇧🇾', dialCode: '+375', isoCode: 'BY'),
    Country(name: 'Belgium', flag: '🇧🇪', dialCode: '+32', isoCode: 'BE'),
    Country(name: 'Belize', flag: '🇧🇿', dialCode: '+501', isoCode: 'BZ'),
    Country(name: 'Benin', flag: '🇧🇯', dialCode: '+229', isoCode: 'BJ'),
    Country(name: 'Bhutan', flag: '🇧🇹', dialCode: '+975', isoCode: 'BT'),
    Country(name: 'Bolivia', flag: '🇧🇴', dialCode: '+591', isoCode: 'BO'),
    Country(name: 'Bosnia and Herzegovina', flag: '🇧🇦', dialCode: '+387', isoCode: 'BA'),
    Country(name: 'Botswana', flag: '🇧🇼', dialCode: '+267', isoCode: 'BW'),
    Country(name: 'Brazil', flag: '🇧🇷', dialCode: '+55', isoCode: 'BR'),
    Country(name: 'Brunei', flag: '🇧🇳', dialCode: '+673', isoCode: 'BN'),
    Country(name: 'Bulgaria', flag: '🇧🇬', dialCode: '+359', isoCode: 'BG'),
    Country(name: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226', isoCode: 'BF'),
    Country(name: 'Burundi', flag: '🇧🇮', dialCode: '+257', isoCode: 'BI'),
    Country(name: 'Cambodia', flag: '🇰🇭', dialCode: '+855', isoCode: 'KH'),
    Country(name: 'Cameroon', flag: '🇨🇲', dialCode: '+237', isoCode: 'CM'),
    Country(name: 'Canada', flag: '🇨🇦', dialCode: '+1', isoCode: 'CA'),
    Country(name: 'Cape Verde', flag: '🇨🇻', dialCode: '+238', isoCode: 'CV'),
    Country(name: 'Central African Republic', flag: '🇨🇫', dialCode: '+236', isoCode: 'CF'),
    Country(name: 'Chad', flag: '🇹🇩', dialCode: '+235', isoCode: 'TD'),
    Country(name: 'Chile', flag: '🇨🇱', dialCode: '+56', isoCode: 'CL'),
    Country(name: 'China', flag: '🇨🇳', dialCode: '+86', isoCode: 'CN'),
    Country(name: 'Colombia', flag: '🇨🇴', dialCode: '+57', isoCode: 'CO'),
    Country(name: 'Comoros', flag: '🇰🇲', dialCode: '+269', isoCode: 'KM'),
    Country(name: 'Congo (Brazzaville)', flag: '🇨🇬', dialCode: '+242', isoCode: 'CG'),
    Country(name: 'Congo (Kinshasa)', flag: '🇨🇩', dialCode: '+243', isoCode: 'CD'),
    Country(name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506', isoCode: 'CR'),
    Country(name: 'Croatia', flag: '🇭🇷', dialCode: '+385', isoCode: 'HR'),
    Country(name: 'Cuba', flag: '🇨🇺', dialCode: '+53', isoCode: 'CU'),
    Country(name: 'Cyprus', flag: '🇨🇾', dialCode: '+357', isoCode: 'CY'),
    Country(name: 'Czech Republic', flag: '🇨🇿', dialCode: '+420', isoCode: 'CZ'),
    Country(name: 'Denmark', flag: '🇩🇰', dialCode: '+45', isoCode: 'DK'),
    Country(name: 'Djibouti', flag: '🇩🇯', dialCode: '+253', isoCode: 'DJ'),
    Country(name: 'Dominica', flag: '🇩🇲', dialCode: '+1767', isoCode: 'DM'),
    Country(name: 'Dominican Republic', flag: '🇩🇴', dialCode: '+1809', isoCode: 'DO'),
    Country(name: 'Ecuador', flag: '🇪🇨', dialCode: '+593', isoCode: 'EC'),
    Country(name: 'Egypt', flag: '🇪🇬', dialCode: '+20', isoCode: 'EG'),
    Country(name: 'El Salvador', flag: '🇸🇻', dialCode: '+503', isoCode: 'SV'),
    Country(name: 'Equatorial Guinea', flag: '🇬🇶', dialCode: '+240', isoCode: 'GQ'),
    Country(name: 'Eritrea', flag: '🇪🇷', dialCode: '+291', isoCode: 'ER'),
    Country(name: 'Estonia', flag: '🇪🇪', dialCode: '+372', isoCode: 'EE'),
    Country(name: 'Eswatini', flag: '🇸🇿', dialCode: '+268', isoCode: 'SZ'),
    Country(name: 'Ethiopia', flag: '🇪🇹', dialCode: '+251', isoCode: 'ET'),
    Country(name: 'Fiji', flag: '🇫🇯', dialCode: '+679', isoCode: 'FJ'),
    Country(name: 'Finland', flag: '🇫🇮', dialCode: '+358', isoCode: 'FI'),
    Country(name: 'France', flag: '🇫🇷', dialCode: '+33', isoCode: 'FR'),
    Country(name: 'Gabon', flag: '🇬🇦', dialCode: '+241', isoCode: 'GA'),
    Country(name: 'Gambia', flag: '🇬🇲', dialCode: '+220', isoCode: 'GM'),
    Country(name: 'Georgia', flag: '🇬🇪', dialCode: '+995', isoCode: 'GE'),
    Country(name: 'Germany', flag: '🇩🇪', dialCode: '+49', isoCode: 'DE'),
    Country(name: 'Ghana', flag: '🇬🇭', dialCode: '+233', isoCode: 'GH'),
    Country(name: 'Greece', flag: '🇬🇷', dialCode: '+30', isoCode: 'GR'),
    Country(name: 'Grenada', flag: '🇬🇩', dialCode: '+1473', isoCode: 'GD'),
    Country(name: 'Guatemala', flag: '🇬🇹', dialCode: '+502', isoCode: 'GT'),
    Country(name: 'Guinea', flag: '🇬🇳', dialCode: '+224', isoCode: 'GN'),
    Country(name: 'Guinea-Bissau', flag: '🇬🇼', dialCode: '+245', isoCode: 'GW'),
    Country(name: 'Guyana', flag: '🇬🇾', dialCode: '+592', isoCode: 'GY'),
    Country(name: 'Haiti', flag: '🇭🇹', dialCode: '+509', isoCode: 'HT'),
    Country(name: 'Honduras', flag: '🇭🇳', dialCode: '+504', isoCode: 'HN'),
    Country(name: 'Hong Kong', flag: '🇭🇰', dialCode: '+852', isoCode: 'HK'),
    Country(name: 'Hungary', flag: '🇭🇺', dialCode: '+36', isoCode: 'HU'),
    Country(name: 'Iceland', flag: '🇮🇸', dialCode: '+354', isoCode: 'IS'),
    Country(name: 'India', flag: '🇮🇳', dialCode: '+91', isoCode: 'IN'),
    Country(name: 'Indonesia', flag: '🇮🇩', dialCode: '+62', isoCode: 'ID'),
    Country(name: 'Iran', flag: '🇮🇷', dialCode: '+98', isoCode: 'IR'),
    Country(name: 'Iraq', flag: '🇮🇶', dialCode: '+964', isoCode: 'IQ'),
    Country(name: 'Ireland', flag: '🇮🇪', dialCode: '+353', isoCode: 'IE'),
    Country(name: 'Israel', flag: '🇮🇱', dialCode: '+972', isoCode: 'IL'),
    Country(name: 'Italy', flag: '🇮🇹', dialCode: '+39', isoCode: 'IT'),
    Country(name: 'Ivory Coast', flag: '🇨🇮', dialCode: '+225', isoCode: 'CI'),
    Country(name: 'Jamaica', flag: '🇯🇲', dialCode: '+1876', isoCode: 'JM'),
    Country(name: 'Japan', flag: '🇯🇵', dialCode: '+81', isoCode: 'JP'),
    Country(name: 'Jordan', flag: '🇯🇴', dialCode: '+962', isoCode: 'JO'),
    Country(name: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7', isoCode: 'KZ'),
    Country(name: 'Kenya', flag: '🇰🇪', dialCode: '+254', isoCode: 'KE'),
    Country(name: 'Kiribati', flag: '🇰🇮', dialCode: '+686', isoCode: 'KI'),
    Country(name: 'Kosovo', flag: '🇽🇰', dialCode: '+383', isoCode: 'XK'),
    Country(name: 'Kuwait', flag: '🇰🇼', dialCode: '+965', isoCode: 'KW'),
    Country(name: 'Kyrgyzstan', flag: '🇰🇬', dialCode: '+996', isoCode: 'KG'),
    Country(name: 'Laos', flag: '🇱🇦', dialCode: '+856', isoCode: 'LA'),
    Country(name: 'Latvia', flag: '🇱🇻', dialCode: '+371', isoCode: 'LV'),
    Country(name: 'Lebanon', flag: '🇱🇧', dialCode: '+961', isoCode: 'LB'),
    Country(name: 'Lesotho', flag: '🇱🇸', dialCode: '+266', isoCode: 'LS'),
    Country(name: 'Liberia', flag: '🇱🇷', dialCode: '+231', isoCode: 'LR'),
    Country(name: 'Libya', flag: '🇱🇾', dialCode: '+218', isoCode: 'LY'),
    Country(name: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423', isoCode: 'LI'),
    Country(name: 'Lithuania', flag: '🇱🇹', dialCode: '+370', isoCode: 'LT'),
    Country(name: 'Luxembourg', flag: '🇱🇺', dialCode: '+352', isoCode: 'LU'),
    Country(name: 'Macau', flag: '🇲🇴', dialCode: '+853', isoCode: 'MO'),
    Country(name: 'Madagascar', flag: '🇲🇬', dialCode: '+261', isoCode: 'MG'),
    Country(name: 'Malawi', flag: '🇲🇼', dialCode: '+265', isoCode: 'MW'),
    Country(name: 'Malaysia', flag: '🇲🇾', dialCode: '+60', isoCode: 'MY'),
    Country(name: 'Maldives', flag: '🇲🇻', dialCode: '+960', isoCode: 'MV'),
    Country(name: 'Mali', flag: '🇲🇱', dialCode: '+223', isoCode: 'ML'),
    Country(name: 'Malta', flag: '🇲🇹', dialCode: '+356', isoCode: 'MT'),
    Country(name: 'Marshall Islands', flag: '🇲🇭', dialCode: '+692', isoCode: 'MH'),
    Country(name: 'Mauritania', flag: '🇲🇷', dialCode: '+222', isoCode: 'MR'),
    Country(name: 'Mauritius', flag: '🇲🇺', dialCode: '+230', isoCode: 'MU'),
    Country(name: 'Mexico', flag: '🇲🇽', dialCode: '+52', isoCode: 'MX'),
    Country(name: 'Micronesia', flag: '🇫🇲', dialCode: '+691', isoCode: 'FM'),
    Country(name: 'Moldova', flag: '🇲🇩', dialCode: '+373', isoCode: 'MD'),
    Country(name: 'Monaco', flag: '🇲🇨', dialCode: '+377', isoCode: 'MC'),
    Country(name: 'Mongolia', flag: '🇲🇳', dialCode: '+976', isoCode: 'MN'),
    Country(name: 'Montenegro', flag: '🇲🇪', dialCode: '+382', isoCode: 'ME'),
    Country(name: 'Morocco', flag: '🇲🇦', dialCode: '+212', isoCode: 'MA'),
    Country(name: 'Mozambique', flag: '🇲🇿', dialCode: '+258', isoCode: 'MZ'),
    Country(name: 'Myanmar (Burma)', flag: '🇲🇲', dialCode: '+95', isoCode: 'MM'),
    Country(name: 'Namibia', flag: '🇳🇦', dialCode: '+264', isoCode: 'NA'),
    Country(name: 'Nauru', flag: '🇳🇷', dialCode: '+674', isoCode: 'NR'),
    Country(name: 'Nepal', flag: '🇳🇵', dialCode: '+977', isoCode: 'NP'),
    Country(name: 'Netherlands', flag: '🇳🇱', dialCode: '+31', isoCode: 'NL'),
    Country(name: 'New Zealand', flag: '🇳🇿', dialCode: '+64', isoCode: 'NZ'),
    Country(name: 'Nicaragua', flag: '🇳🇮', dialCode: '+505', isoCode: 'NI'),
    Country(name: 'Niger', flag: '🇳🇪', dialCode: '+227', isoCode: 'NE'),
    Country(name: 'Nigeria', flag: '🇳🇬', dialCode: '+234', isoCode: 'NG'),
    Country(name: 'North Korea', flag: '🇰🇵', dialCode: '+850', isoCode: 'KP'),
    Country(name: 'North Macedonia', flag: '🇲🇰', dialCode: '+389', isoCode: 'MK'),
    Country(name: 'Norway', flag: '🇳🇴', dialCode: '+47', isoCode: 'NO'),
    Country(name: 'Oman', flag: '🇴🇲', dialCode: '+968', isoCode: 'OM'),
    Country(name: 'Pakistan', flag: '🇵🇰', dialCode: '+92', isoCode: 'PK'),
    Country(name: 'Palau', flag: '🇵🇼', dialCode: '+680', isoCode: 'PW'),
    Country(name: 'Palestine', flag: '🇵🇸', dialCode: '+970', isoCode: 'PS'),
    Country(name: 'Panama', flag: '🇵🇦', dialCode: '+507', isoCode: 'PA'),
    Country(name: 'Papua New Guinea', flag: '🇵🇬', dialCode: '+675', isoCode: 'PG'),
    Country(name: 'Paraguay', flag: '🇵🇾', dialCode: '+595', isoCode: 'PY'),
    Country(name: 'Peru', flag: '🇵🇪', dialCode: '+51', isoCode: 'PE'),
    Country(name: 'Philippines', flag: '🇵🇭', dialCode: '+63', isoCode: 'PH'),
    Country(name: 'Poland', flag: '🇵🇱', dialCode: '+48', isoCode: 'PL'),
    Country(name: 'Portugal', flag: '🇵🇹', dialCode: '+351', isoCode: 'PT'),
    Country(name: 'Qatar', flag: '🇶🇦', dialCode: '+974', isoCode: 'QA'),
    Country(name: 'Romania', flag: '🇷🇴', dialCode: '+40', isoCode: 'RO'),
    Country(name: 'Russia', flag: '🇷🇺', dialCode: '+7', isoCode: 'RU'),
    Country(name: 'Rwanda', flag: '🇷🇼', dialCode: '+250', isoCode: 'RW'),
    Country(name: 'Saint Kitts and Nevis', flag: '🇰🇳', dialCode: '+1869', isoCode: 'KN'),
    Country(name: 'Saint Lucia', flag: '🇱🇨', dialCode: '+1758', isoCode: 'LC'),
    Country(name: 'Samoa', flag: '🇼🇸', dialCode: '+685', isoCode: 'WS'),
    Country(name: 'San Marino', flag: '🇸🇲', dialCode: '+378', isoCode: 'SM'),
    Country(name: 'Sao Tome and Principe', flag: '🇸🇹', dialCode: '+239', isoCode: 'ST'),
    Country(name: 'Saudi Arabia', flag: '🇸🇦', dialCode: '+966', isoCode: 'SA'),
    Country(name: 'Senegal', flag: '🇸🇳', dialCode: '+221', isoCode: 'SN'),
    Country(name: 'Serbia', flag: '🇷🇸', dialCode: '+381', isoCode: 'RS'),
    Country(name: 'Seychelles', flag: '🇸🇨', dialCode: '+248', isoCode: 'SC'),
    Country(name: 'Sierra Leone', flag: '🇸🇱', dialCode: '+232', isoCode: 'SL'),
    Country(name: 'Singapore', flag: '🇸🇬', dialCode: '+65', isoCode: 'SG'),
    Country(name: 'Slovakia', flag: '🇸🇰', dialCode: '+421', isoCode: 'SK'),
    Country(name: 'Slovenia', flag: '🇸🇮', dialCode: '+386', isoCode: 'SI'),
    Country(name: 'Solomon Islands', flag: '🇸🇧', dialCode: '+677', isoCode: 'SB'),
    Country(name: 'Somalia', flag: '🇸🇴', dialCode: '+252', isoCode: 'SO'),
    Country(name: 'South Africa', flag: '🇿🇦', dialCode: '+27', isoCode: 'ZA'),
    Country(name: 'South Korea', flag: '🇰🇷', dialCode: '+82', isoCode: 'KR'),
    Country(name: 'South Sudan', flag: '🇸🇸', dialCode: '+211', isoCode: 'SS'),
    Country(name: 'Spain', flag: '🇪🇸', dialCode: '+34', isoCode: 'ES'),
    Country(name: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94', isoCode: 'LK'),
    Country(name: 'Sudan', flag: '🇸🇩', dialCode: '+249', isoCode: 'SD'),
    Country(name: 'Suriname', flag: '🇸🇷', dialCode: '+597', isoCode: 'SR'),
    Country(name: 'Sweden', flag: '🇸🇪', dialCode: '+46', isoCode: 'SE'),
    Country(name: 'Switzerland', flag: '🇨🇭', dialCode: '+41', isoCode: 'CH'),
    Country(name: 'Syria', flag: '🇸🇾', dialCode: '+963', isoCode: 'SY'),
    Country(name: 'Taiwan', flag: '🇹🇼', dialCode: '+886', isoCode: 'TW'),
    Country(name: 'Tajikistan', flag: '🇹🇯', dialCode: '+992', isoCode: 'TJ'),
    Country(name: 'Tanzania', flag: '🇹🇿', dialCode: '+255', isoCode: 'TZ'),
    Country(name: 'Thailand', flag: '🇹🇭', dialCode: '+66', isoCode: 'TH'),
    Country(name: 'Timor-Leste', flag: '🇹🇱', dialCode: '+670', isoCode: 'TL'),
    Country(name: 'Togo', flag: '🇹🇬', dialCode: '+228', isoCode: 'TG'),
    Country(name: 'Tonga', flag: '🇹🇴', dialCode: '+676', isoCode: 'TO'),
    Country(name: 'Trinidad and Tobago', flag: '🇹🇹', dialCode: '+1868', isoCode: 'TT'),
    Country(name: 'Tunisia', flag: '🇹🇳', dialCode: '+216', isoCode: 'TN'),
    Country(name: 'Turkey', flag: '🇹🇷', dialCode: '+90', isoCode: 'TR'),
    Country(name: 'Turkmenistan', flag: '🇹🇲', dialCode: '+993', isoCode: 'TM'),
    Country(name: 'Tuvalu', flag: '🇹🇻', dialCode: '+688', isoCode: 'TV'),
    Country(name: 'Uganda', flag: '🇺🇬', dialCode: '+256', isoCode: 'UG'),
    Country(name: 'Ukraine', flag: '🇺🇰', dialCode: '+380', isoCode: 'UA'),
    Country(name: 'United Arab Emirates', flag: '🇦🇪', dialCode: '+971', isoCode: 'AE'),
    Country(name: 'United Kingdom', flag: '🇬🇧', dialCode: '+44', isoCode: 'GB'),
    Country(name: 'United States', flag: '🇺🇸', dialCode: '+1', isoCode: 'US'),
    Country(name: 'Uruguay', flag: '🇺🇾', dialCode: '+598', isoCode: 'UY'),
    Country(name: 'Uzbekistan', flag: '🇺🇿', dialCode: '+998', isoCode: 'UZ'),
    Country(name: 'Vanuatu', flag: '🇻🇺', dialCode: '+678', isoCode: 'VU'),
    Country(name: 'Vatican City', flag: '🇻🇦', dialCode: '+379', isoCode: 'VA'),
    Country(name: 'Venezuela', flag: '🇻🇪', dialCode: '+58', isoCode: 'VE'),
    Country(name: 'Vietnam', flag: '🇻🇳', dialCode: '+84', isoCode: 'VN'),
    Country(name: 'Yemen', flag: '🇾🇪', dialCode: '+967', isoCode: 'YE'),
    Country(name: 'Zambia', flag: '🇿🇲', dialCode: '+260', isoCode: 'ZM'),
    Country(name: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263', isoCode: 'ZW'),
  ];

  static Country defaultCountry = countries.firstWhere(
    (c) => c.isoCode == 'TZ',
    orElse: () => countries.first,
  );

  static List<Country> search(String query) {
    if (query.isEmpty) return countries;
    final q = query.toLowerCase();
    return countries
        .where((c) =>
            c.name.toLowerCase().contains(q) ||
            c.dialCode.contains(q) ||
            c.isoCode.toLowerCase().contains(q))
        .toList();
  }
}
